# MySQL connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update

# ---------------- Razorpay (TEST MODE ONLY) ----------------
razorpay.keyId=rzp_test_SZwx2hh8vHJnkS
razorpay.keySecret=BuxmPmh0YWrtVtYBo4G05Kly
razorpay.webhookSecret=eventplanner_test_webhook